server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: info,health,startup
  endpoint:
    health:
      show-details: always

spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:guideline;DB_CLOSE_ON_EXIT=FALSE;INIT=RUNSCRIPT FROM 'classpath:db-setup.sql'
    username: sa
    password:
    initialization-mode: never