apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grpc-client
  name: grpc-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-client
  template:
    metadata:
      labels:
        app: grpc-client
    spec:
      containers:
        - name: grpc-client
          image: anjeyy/unbendable:grpc-sample-client-latest
          ports:
            - name: rest
              containerPort: 7070
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
            - name: GRPC_SERVER_PORT
              value: '-1'
#---
# TODO via config not working
#apiVersion: v1
#kind: Service
#metadata:
#  name: grpc-client
#spec:
#  selector:
#    app: grpc-client
#  type: LoadBalancer
#  ports:
#    - port: 7070
#      targetPort: rest
