apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grpc-simple-app
  name: grpc-client
spec:
  replicas: 3
  selector:
    matchLabels:
      app: grpc-simple-app
  template:
    metadata:
      labels:
        app: grpc-simple-app
    spec:
      containers:
        - name: grpc-client
          image: anjeyy/unbendable:grpc-sample-client-latest
          ports:
            - name: rest
              containerPort: 7070
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
            - name: GRPC_SERVER_PORT
              value: '-1'
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-client
spec:
  selector:
    app: grpc-simple-app
  type: LoadBalancer
  ports:
    - port: 8088

