server:
  port: 7070

management:
  endpoints:
    web:
      exposure:
        include: info,health,startup
  endpoint:
    health:
      show-details: always


spring:
  application:
    name: my-grpc-client


# how to set dynamic addresses
# https://yidongnan.github.io/grpc-spring-boot-starter/en/client/configuration.html
grpc:
  client:
    hello-service:
      address: static://localhost:9090
      negotiationType: plaintext
    document-service:
      address: static://localhost:9090
      negotiationType: plaintext
  server:
    port: -1