server:
  port: 7070

management:
  endpoints:
    web:
      exposure:
        include: info,health,startup
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: my-grpc-client
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    sender:
      type: grpc

grpc:
  client:
    hello-service:
      address: static://localhost:9090
      negotiationType: plaintext
    document-service:
      address: static://localhost:9090
      negotiationType: plaintext