server:
  port: 7070

management:
  endpoints:
    web:
      exposure:
        include: info,health,startup
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: my-grpc-client


grpc:
  client:
    hello-service:
      address: static://localhost:9090
      negotiationType: plaintext
    document-service:
      address: static://localhost:9090
      negotiationType: plaintext
  server:
    port: -1