name: Publish Docker images
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-jar:
    name: Test & build artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

      - name: Save artifacts for other jobs
        run: |
          mkdir -p path/to/artifact
          cp ./grpc-client/target/grpc-client*.jar path/to/artifact
          cp ./grpc-server/target/grpc-server*.jar path/to/artifact
          ls -la path/to/artifact

      - name: Upload saved artifacts
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: path/to/artifact
          retention-days: 1
          if-no-files-found: error

  push-client-to-registry:
    name: Client Docker Build & Push
    runs-on: ubuntu-latest
    needs:
      - build-jar
    #      TODO revert
    #    if: github.event.pull_request.merged == true
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: my-artifact
          path: path/to/artifact

      - name: Create directory and copy artifacts
        run: |
          mkdir -p grpc-client/target
          mkdir -p grpc-server/target
          cp path/to/artifact/grpc-client*.jar grpc-client/target
          cp path/to/artifact/grpc-server*.jar grpc-server/target
          ls -la grpc-client/target
          ls -la grpc-server/target

      - name: Debug
        run: |
          ls -la .

      - name: Build & Push [Client] to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./grpc-client
          file: ./grpc-client/Dockerfile
          tags: anjeyy/unbendable:grpc-sample-client-latest
          pull: true
          push: true
          no-cache: true

  push-server-to-registry:
    name: Server Docker Build & Push
    runs-on: ubuntu-latest
    needs:
      #      - push-client-to-registry
      - build-jar
    #      TODO revert
    #    if: github.event.pull_request.merged == true
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: my-artifact
          path: path/to/artifact

      - name: Create directory and copy artifacts
        run: |
          mkdir -p grpc-server/target
          cp path/to/artifact/grpc-server*.jar grpc-server/target
          ls -la grpc-server/target

      - name: Debug
        run: |
          ls -la .

      - name: Build & Push [Server] to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./grpc-server
          file: ./grpc-server/Dockerfile
          tags: anjeyy/unbendable:grpc-sample-server-latest
          pull: true
          push: true
          no-cache: true
