name: Publish Docker images
on:
  # TODO clean up file and split approrpiately
  #  uncomment after workflow is working
  #  release:
  #    types: [ published ]
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_jar:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      # save artifacts for other jobs
      - run: mkdir -p path/to/artifact
      - run: cp ./grpc-client/target/grpc-client*.jar path/to/artifact
      - run: cp ./grpc-server/target/grpc-server*.jar path/to/artifact
      - run: ls -la path/to/artifact
      - uses: actions/upload-artifact@master
        with:
          name: my-artifact
          path: path/to/artifact

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs:
      - build_jar
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - run: mkdir -p target
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: my-artifact
          path: path/to/artifact
      - run: cp path/to/artifact/* target

      - name: Build & Push [Client] to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./grpc-client/Dockerfile
          tags: anjeyy/unbendable:grpc-sample-client-latest
          pull: true
          push: true
          build-args: |
            arg1=value1
            arg2=value2
      - name: Build & Push [Server] to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./grpc-server/Dockerfile
          tags: anjeyy/unbendable:grpc-sample-server-latest
          pull: true
          push: true
          build-args: |
            arg1=value1
            arg2=value2
