name: Publish Docker images
on:
  #  uncomment after workflow is working
  #  release:
  #    types: [ published ]
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push [Client] to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./grpc-client/Dockerfile
          tags: anjeyy/unbendable:grpc-sample-client-latest
          pull: true
          push: true
          build-args: |
            arg1=value1
            arg2=value2
      - name: Build & Push [Server] to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./grpc-server/Dockerfile
          tags: anjeyy/unbendable:grpc-sample-server-latest
          pull: true
          push: true
          build-args: |
            arg1=value1
            arg2=value2
